### PR TITLE
Build with GHC 8.8

### PR DESCRIPTION
**Pull request by raehik**
We're using this over in [camfort/verifiable-expressions](https://github.com/camfort/verifiable-expressions) (I say *we*, I'm new to the project and currently doing maintenance), and need to bump union's dependencies to get our projects building with newer GHCs. Thank you for the library!

### CODE REVIEW

**Comment by raehik** [comment]
I realise we might be able to accomplish this with a Hackage metadata update, but I don't have many insights on how that might work.

**Comment by int-index** [comment]
Thanks for the PR! Since this is to support a newer compiler version, I wanted to check that on CI, but the existing CI was somewhat outdated so I switched to GitHub Actions in #10. Then I incorporated the proposed version bounds in #11.

> I realise we might be able to accomplish this with a Hackage metadata update, but I don't have many insights on how that might work.

Done. Check out `union-0.1.2` revision 5. Does it work for you?

**Comment by raehik** [comment]
It does, thank you! Would you know if [the Stackage page](https://www.stackage.org/package/union) will update its version to use revision 5 after a nightly or something?

**Comment by raehik** [comment]
Ah, nevermind, I found Stack's revision pinning syntax so I'll use that. Thanks again! I'll close this PR.

**Pull request closed without merging**
